In [2]:
import pandas as pd
import yfinance as yf

In [3]:
start = '2021-01-01'
end = '2022-01-01'

In [4]:
data_price_condition = yf.download('BTC-USD', start='2021-01-01', end='2022-05-01')

[*********************100%***********************]  1 of 1 completed

In [5]:
df_price_condition = data_price_condition.copy()

In [6]:
df_price_condition['Return']= df_price_condition['Close'].pct_change()

In [7]:
df_price_condition

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-01-01,28994.009766,29600.626953,28803.585938,29374.152344,29374.152344,40730301359,NaN
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765,0.093726
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202,0.020380
2021-01-04,32810.949219,33440.218750,28722.755859,31971.914062,31971.914062,81163475344,-0.024712
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782,0.063197
...,...,...,...,...,...,...,...
2022-04-26,40448.421875,40713.890625,37884.984375,38117.460938,38117.460938,34569088416,-0.057858
2022-04-27,38120.300781,39397.917969,37997.312500,39241.121094,39241.121094,30981015184,0.029479
2022-04-28,39241.429688,40269.464844,38941.421875,39773.828125,39773.828125,33903704907,0.013575
2022-04-29,39768.617188,39887.269531,38235.535156,38609.824219,38609.824219,30882994649,-0.029266
2022-04-30,38605.859375,38771.210938,37697.941406,37714.875000,37714.875000,23895713731,-0.023179

In [8]:
df_price_condition[df_price_condition['Close']>60000]

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-03-13,57343.371094,61683.863281,56217.972656,61243.085938,61243.085938,60669829814,0.068217
2021-04-11,59846.230469,60790.554688,59289.796875,60204.964844,60204.964844,46280252580,0.006886
2021-04-13,59890.019531,63742.285156,59869.957031,63503.457031,63503.457031,69983454362,0.060274
2021-04-14,63523.753906,64863.097656,61554.796875,63109.695312,63109.695312,77451779687,-0.006201
2021-04-15,63075.195312,63821.671875,62208.964844,63314.011719,63314.011719,60954381579,0.003237
2021-04-16,63258.503906,63594.722656,60222.531250,61572.789062,61572.789062,84293007468,-0.027501
2021-04-17,61529.921875,62572.175781,60361.351562,60683.820312,60683.820312,66138759198,-0.014438
2021-10-15,57345.902344,62757.128906,56868.144531,61593.949219,61593.949219,51780081801,0.074534
2021-10-16,61609.527344,62274.476562,60206.121094,60892.179688,60892.179688,34250964237,-0.011393
2021-10-17,60887.652344,61645.523438,59164.468750,61553.617188,61553.617188,29032367511,0.010862
2021-10-18,61548.804688,62614.660156,60012.757812,62026.078125,62026.078125,38055562075,0.007676
2021-10-19,62043.164062,64434.535156,61622.933594,64261.992188,64261.992188,40471196346,0.036048
2021-10-20,64284.585938,66930.390625,63610.675781,65992.835938,65992.835938,40788955582,0.026934
2021-10-21,66002.234375,66600.546875,62117.410156,62210.171875,62210.171875,45908121370,-0.057319
2021-10-22,62237.890625,63715.023438,60122.796875,60692.265625,60692.265625,38434082775,-0.024400
2021-10-23,60694.628906,61743.878906,59826.523438,61393.617188,61393.617188,26882546034,0.011556
2021-10-24,61368.343750,61505.804688,59643.343750,60930.835938,60930.835938,27316183882,-0.007538
2021-10-25,60893.925781,63729.324219,60691.800781,63039.824219,63039.824219,31064911614,0.034613
2021-10-26,63032.761719,63229.027344,59991.160156,60363.792969,60363.792969,34878965587,-0.042450
2021-10-28,58470.730469,62128.632812,58206.917969,60622.136719,60622.136719,45257083247,0.036588
2021-10-29,60624.871094,62927.609375,60329.964844,62227.964844,62227.964844,36856881767,0.026489
2021-10-30,62239.363281,62330.144531,60918.386719,61888.832031,61888.832031,32157938616,-0.005450
2021-10-31,61850.488281,62406.171875,60074.328125,61318.957031,61318.957031,32241199927,-0.009208
2021-11-01,61320.449219,62419.003906,59695.183594,61004.406250,61004.406250,36150572843,-0.005130
2021-11-02,60963.253906,64242.792969,60673.054688,63226.402344,63226.402344,37746665647,0.036424
2021-11-03,63254.335938,63516.937500,61184.238281,62970.046875,62970.046875,36124731509,-0.004055
2021-11-04,62941.804688,63123.289062,60799.664062,61452.230469,61452.230469,32615846901,-0.024104
2021-11-05,61460.078125,62541.468750,60844.609375,61125.675781,61125.675781,30605102446,-0.005314
2021-11-06,61068.875000,61590.683594,60163.781250,61527.480469,61527.480469,29094934221,0.006573
2021-11-07,61554.921875,63326.988281,61432.488281,63326.988281,63326.988281,24726754302,0.029247
2021-11-08,63344.066406,67673.742188,63344.066406,67566.828125,67566.828125,41125608330,0.066952
2021-11-09,67549.734375,68530.335938,66382.062500,66971.828125,66971.828125,42357991721,-0.008806
2021-11-10,66953.335938,68789.625000,63208.113281,64995.230469,64995.230469,48730828378,-0.029514
2021-11-11,64978.890625,65579.015625,64180.488281,64949.960938,64949.960938,35880633236,-0.000697
2021-11-12,64863.980469,65460.816406,62333.914062,64155.941406,64155.941406,36084893887,-0.012225
2021-11-13,64158.121094,64915.675781,63303.734375,64469.527344,64469.527344,30474228777,0.004888
2021-11-14,64455.371094,65495.179688,63647.808594,65466.839844,65466.839844,25122092191,0.015470
2021-11-15,65521.289062,66281.570312,63548.144531,63557.871094,63557.871094,30558763548,-0.029159
2021-11-16,63721.195312,63721.195312,59016.335938,60161.246094,60161.246094,46844335592,-0.053441
2021-11-17,60139.621094,60823.609375,58515.410156,60368.011719,60368.011719,39178392930,0.003437

In [9]:
df_price_condition[df_price_condition.Return>0]

,Open,High,Low,Close,Adj Close,Volume,Return
Date,,,,,,,
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765,0.093726
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202,0.020380
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782,0.063197
2021-01-06,34013.613281,36879.699219,33514.035156,36824.363281,36824.363281,75289433811,0.083311
2021-01-07,36833.875000,40180.367188,36491.191406,39371.042969,39371.042969,84762141031,0.069157
...,...,...,...,...,...,...,...
2022-04-18,39721.203125,40986.320312,38696.191406,40826.214844,40826.214844,33705182072,0.027929
2022-04-19,40828.175781,41672.960938,40618.632812,41502.750000,41502.750000,25303206547,0.016571
2022-04-25,39472.605469,40491.753906,38338.378906,40458.308594,40458.308594,35445730570,0.025058
2022-04-27,38120.300781,39397.917969,37997.312500,39241.121094,39241.121094,30981015184,0.029479
2022-04-28,39241.429688,40269.464844,38941.421875,39773.828125,39773.828125,33903704907,0.013575

In [10]:
def checkGainLoss(df_return):
    if df_return > 0:
        return 'Gain'
    elif pd.isna(df_return):
        return 'Unknown'
    else:
        return 'Loss'

In [11]:
df_price_condition['result']=df_price_condition.Return.map(checkGainLoss)

In [13]:
df_price_condition.dropna(inplace=True)

In [14]:
df_price_condition

,Open,High,Low,Close,Adj Close,Volume,Return,result
Date,,,,,,,,
2021-01-02,29376.455078,33155.117188,29091.181641,32127.267578,32127.267578,67865420765,0.093726,Gain
2021-01-03,32129.408203,34608.558594,32052.316406,32782.023438,32782.023438,78665235202,0.020380,Gain
2021-01-04,32810.949219,33440.218750,28722.755859,31971.914062,31971.914062,81163475344,-0.024712,Loss
2021-01-05,31977.041016,34437.589844,30221.187500,33992.429688,33992.429688,67547324782,0.063197,Gain
2021-01-06,34013.613281,36879.699219,33514.035156,36824.363281,36824.363281,75289433811,0.083311,Gain
...,...,...,...,...,...,...,...,...
2022-04-26,40448.421875,40713.890625,37884.984375,38117.460938,38117.460938,34569088416,-0.057858,Loss
2022-04-27,38120.300781,39397.917969,37997.312500,39241.121094,39241.121094,30981015184,0.029479,Gain
2022-04-28,39241.429688,40269.464844,38941.421875,39773.828125,39773.828125,33903704907,0.013575,Gain
2022-04-29,39768.617188,39887.269531,38235.535156,38609.824219,38609.824219,30882994649,-0.029266,Loss
2022-04-30,38605.859375,38771.210938,37697.941406,37714.875000,37714.875000,23895713731,-0.023179,Loss